name: K6 Performance Load

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up K6
        uses: grafana/k6-action@v1
        with:
          version: 'latest'

      - name: Run K6
        run: k6 run load.js